name: Planetary Computer APIs PR CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run cibuild
        run: ./scripts/cibuild
      
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ fromJSON(secrets.SECURE_AZURE_CREDENTIALS).clientId }}
          tenant-id: ${{ fromJSON(secrets.SECURE_AZURE_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJSON(secrets.SECURE_AZURE_CREDENTIALS).subscriptionId }}

      - name: 'Run Azure CLI commands'
        run: |
            az account show
            az group list
            pwd 
            
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10" # stac-api-validator requires >= 3.10
          cache: "pip"
      - name: Validate
        run: ./scripts/validate
