name: Planetary Computer APIs PR CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Azurite Default Key
        run: echo "AZURITE_ACCOUNT_KEY=$(curl https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite | grep "Account key:" | cut -b 24-111)" >> $GITHUB_ENV

      - name: Verify Azurite Key was retrieved correctly
        if: ($AZURITE_ACCOUNT_KEY | cut -b 1-4) == 'Eby8'
        run: echo GOT HERE

      - name: Run cibuild
        run: ./scripts/cibuild

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10" # stac-api-validator requires >= 3.10
          cache: "pip"

      - name: Set Azurite Default Key
        run: echo "AZURITE_ACCOUNT_KEY=$(curl https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite | grep "Account key:" | cut -b 24-111)" >> $GITHUB_ENV

      - name: Validate
        run: ./scripts/validate
